services:
  - type: web
    name: daft-backend
    env: python
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT --proxy-headers
    envVars:
      - key: MONGODB_URL
        sync: false
      - key: SECRET_KEY
        sync: false
    buildFilter:
      paths:
        - backend/**
